version: '3.7'

services:
  db:
    container_name: localpostgres
    image: postgres:latest
    environment:
      - POSTGRES_HOST=localpostgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ad_campaigns
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql

  queue:
    container_name: localredis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --save 60 1 --loglevel warning

  app:
    container_name: campaign-reports
    image: node:20
    working_dir: /app
    command: bash -c "npm i && npm run migration:run && npm start"
    ports:
      - 3000:3000
    volumes:
      - ../src:/app/src
      - ../processor.js:/app/processor.js
      - ../.logs:/app/.logs
      - ../.env.docker:/app/.env
      - ../package.json:/app/package.json
      - ../node_modules:/app/node_modules
      - ../nest-cli.json:/app/nest-cli.json
      - ../tsconfig.build.json:/app/tsconfig.build.json
      - ../tsconfig.json:/app/tsconfig.json
    depends_on:
      - db
      - queue
